[grid]
label = "Example"

[grid.time]
divisions = 6

seconds_per_division = 1.0
raw_per_second = 1000.0

label = "1 div = 1 s"

[grid.data]
divisions = 4
zero_shift = -1.0

label = "1 div = 1 g"

[[y]]
raw_offset = 0.0
raw_per_division = 1000.0
