[background]
rgb = [35, 39, 42]

[labels]
rgb = [255, 255, 255]

[grid]
rgb = [255, 255, 255]
opacity = 0.5

[fit]
rgb = [255, 255, 255]

[[channel]] 
rgb = [255, 53, 100]

[[channel]] 
rgb = [255, 255, 200]

[[channel]] 
rgb = [25, 255, 255]

